name: Flutter Test
on: [ push ]
jobs:
  Tests:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[no-tests]') }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.2.3'
      - run: flutter pub get
      - run: flutter config --no-analytics
      - run: flutter test
